version: '3.7'

services:
  db:
    image: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql
    restart: always
    environment:
      POSTGRES_DB: "my-database"
      POSTGRES_USER: "postgres_user"
      POSTGRES_PASSWORD: "password"
    ports:
    - 5432:5432

volumes:
  data: {}